-- 테이블 소스 코드 관리 파일
drop table if exists member CASCADE;
create table member
(
    -- id 값이 null값으로 들어왔을 때, DB에서 id 값을 자동으로 채워줌
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

-- h2에서 데이터 넣을 때 쿼리
-- insert into member(name) values('이름') > values값 안에는 반드시 홑따옴표 사용해야함!